-- KHEM — orders, order lines, and the stock movement they cause.
--
-- Applied by `npm run db:migrate` after the catalog (`0001`) it points at and
-- after the privilege clawback (`0006`) — which is why this file revokes the
-- public grants explicitly at the bottom rather than trusting the altered
-- default privileges to have covered a table created later.
--
-- `src/services/admin/orders.ts` and `src/services/admin/analytics.ts` read
-- these; `src/actions/admin/orders.ts` and `src/actions/admin/inventory.ts`
-- write them. `src/services/account.ts` reads a customer's own orders.
--
-- ── The stock model ─────────────────────────────────────────
--
-- There is exactly one stock number per product: `Product.inventory`, created
-- in `0001_catalog.sql`. The website is the only channel that owns stock.
-- `Order.channel` records where a sale came from — a walk-in typed into the
-- dashboard is `OFFLINE`, a future checkout is `ONLINE` — but both draw the
-- units down from the same column, because there is one shelf.
--
-- Stock moves **here**, never in TypeScript. `place_order()` locks every
-- product row it is about to sell, checks the count, writes the order, and
-- decrements — one transaction. A service that read the count, decided, and
-- then wrote would let two editors each sell the last bottle in the gap
-- between their read and their write. That gap is the entire reason these are
-- functions and not queries.
--
-- ── Trust model ─────────────────────────────────────────────
--
-- Identity is Clerk's, so `auth.uid()` is always null and RLS here cannot
-- express "this order is mine". Same split as `0005_comments.sql`, one notch
-- tighter: RLS is on, there is **no** policy of any kind, and the public roles
-- hold no grant. Nothing reaches these tables except code holding
-- SUPABASE_SECRET_KEY — the dashboard, the account portal's server-side read,
-- and the `scripts/db-*` tooling. A browser cannot read an order at all, which
-- is the correct default for a table holding a customer's name and phone
-- number.
--
-- `execute` on the three functions is revoked from the public roles for the
-- same reason: `place_order` is `security definer`, and a definer function the
-- anon role may call is a write path with the door left open.

-- ── Enums ───────────────────────────────────────────────────
--
-- Members mirror the closed unions in `src/types/account.ts` and
-- `src/types/order.ts`. `OrderStatus` in particular is what the account
-- dictionary is keyed by, so adding a member here without adding the two
-- translations is a compile error on the other side — deliberately.

do $$ begin
  create type public."OrderStatus" as enum (
    'PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public."PaymentStatus" as enum ('UNPAID', 'PAID', 'FAILED', 'REFUNDED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public."OrderChannel" as enum ('ONLINE', 'OFFLINE');
exception when duplicate_object then null; end $$;

-- ── Order ───────────────────────────────────────────────────

-- Human-facing order numbers. Not reset per year: a sequence that restarts
-- would collide with `KHEM-2026-0001` the moment an order is placed on the
-- first of January while another is still being written. The year in the
-- string is the year it was placed; the counter is simply never reused.
create sequence if not exists public.order_number_seq start 1000;

create table if not exists public."Order" (
  id              text primary key default gen_random_uuid()::text,

  -- Generated by the database, never by a client. `KHEM-2026-1042`.
  "orderNumber"   text not null unique
    default 'KHEM-' || to_char(now(), 'YYYY') || '-'
            || lpad(nextval('public.order_number_seq')::text, 4, '0'),

  -- Whoever the order is for. A walk-in has a name and maybe a phone; an
  -- online order will also carry `clerkUserId`, stamped from a verified
  -- session on the server and never from a form field.
  "customerName"  text not null check (char_length("customerName") between 2 and 120),
  "customerEmail" text check (char_length("customerEmail") <= 200),
  "customerPhone" text check (char_length("customerPhone") <= 40),
  "clerkUserId"   text,

  -- The desk's own note: "collected in store", "gift wrap". Never shown to a
  -- customer.
  note            text check (char_length(note) <= 2000),

  status          public."OrderStatus"   not null default 'PENDING',
  "paymentStatus" public."PaymentStatus" not null default 'UNPAID',
  channel         public."OrderChannel"  not null default 'OFFLINE',

  -- Smallest unit of the base currency — piastres, same as
  -- `Product.priceInCents`. See `src/lib/currency.ts`.
  "subtotalInCents" int not null check ("subtotalInCents" >= 0),
  "shipInCents"     int not null default 0 check ("shipInCents" >= 0),
  "totalInCents"    int not null check ("totalInCents" >= 0),

  -- Printed on the customer's order card once the parcel is with the courier.
  -- Null until then, which is what `OrderSummary.trackingCode` means.
  "trackingCode"  text check (char_length("trackingCode") <= 120),

  -- Stamped the one time this order's units go back on the shelf. The guard
  -- that makes CANCELLED → REFUNDED — or a double-click on either — restock
  -- once instead of twice.
  "stockReleasedAt" timestamptz,

  "placedAt"      timestamptz not null default now(),
  "createdAt"     timestamptz not null default now(),
  "updatedAt"     timestamptz not null default now()
);

-- Added rather than assumed: the table may already exist from an earlier run of
-- this file, and `create table if not exists` would skip a new column silently.
alter table public."Order"
  add column if not exists "trackingCode" text;

create index if not exists order_placed_idx
  on public."Order" ("placedAt" desc);
create index if not exists order_status_idx
  on public."Order" (status);
create index if not exists order_channel_placed_idx
  on public."Order" (channel, "placedAt" desc);
create index if not exists order_clerk_user_idx
  on public."Order" ("clerkUserId", "placedAt" desc)
  where "clerkUserId" is not null;

-- ── OrderItem ───────────────────────────────────────────────

create table if not exists public."OrderItem" (
  id            text primary key default gen_random_uuid()::text,

  "orderId"     text not null
    references public."Order"(id) on delete cascade,

  -- Slug is the join key the rest of this schema uses (`ProductImage`,
  -- `product_comment`), so it is the one used here too.
  "productSlug" text not null
    references public."Product"(slug) on update cascade,

  -- A snapshot, not a lookup. A product renamed next season, or archived, must
  -- still print on the order it was sold on. The foreign key keeps the link
  -- for reporting; this keeps the history readable when the link changes.
  "productName" text not null,

  quantity      int not null check (quantity > 0),

  -- The price at the moment of sale. A later catalog edit never rewrites what
  -- somebody was charged.
  "priceInCents" int not null check ("priceInCents" >= 0)
);

create index if not exists order_item_order_idx
  on public."OrderItem" ("orderId");
create index if not exists order_item_product_idx
  on public."OrderItem" ("productSlug");

-- ── place_order ─────────────────────────────────────────────
--
-- The only supported way to create an order. Takes
--
--   { customerName, customerEmail, customerPhone, clerkUserId, channel,
--     note, shipInCents, items: [{ slug, quantity }] }
--
-- and returns the generated order number.
--
-- `security definer` because the caller is the service key today but need not
-- always be, and because the invariant — an order and its stock movement are
-- the same event — should belong to the function rather than to whoever calls
-- it. `search_path` is pinned so a definer function cannot be pointed at a
-- shadowed table.

create or replace function public.place_order(payload jsonb)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id   text;
  v_number     text;
  v_subtotal   int := 0;
  v_ship       int := coalesce((payload->>'shipInCents')::int, 0);
  v_channel    public."OrderChannel" :=
                 coalesce((payload->>'channel')::public."OrderChannel", 'OFFLINE');
  v_item       jsonb;
  v_slug       text;
  v_qty        int;
  v_product    record;
begin
  if jsonb_typeof(payload->'items') <> 'array'
     or jsonb_array_length(payload->'items') = 0 then
    raise exception 'An order needs at least one line.'
      using errcode = 'check_violation';
  end if;

  insert into public."Order" (
    "customerName", "customerEmail", "customerPhone", "clerkUserId",
    note, channel, "subtotalInCents", "shipInCents", "totalInCents"
  ) values (
    payload->>'customerName',
    nullif(payload->>'customerEmail', ''),
    nullif(payload->>'customerPhone', ''),
    nullif(payload->>'clerkUserId', ''),
    nullif(payload->>'note', ''),
    v_channel,
    0, v_ship, 0
  )
  returning id, "orderNumber" into v_order_id, v_number;

  -- Ordered by slug so two concurrent orders touching the same two products
  -- take their locks in the same sequence and one waits instead of both
  -- deadlocking.
  for v_item in
    select value
    from jsonb_array_elements(payload->'items')
    order by value->>'slug'
  loop
    v_slug := v_item->>'slug';
    v_qty  := (v_item->>'quantity')::int;

    if v_qty is null or v_qty < 1 then
      raise exception 'Quantity must be at least 1.'
        using errcode = 'check_violation';
    end if;

    select slug, name, "priceInCents", inventory, "isArchived"
      into v_product
      from public."Product"
     where slug = v_slug
     for update;

    if not found then
      raise exception 'No product with the slug %.', v_slug
        using errcode = 'foreign_key_violation';
    end if;

    if v_product."isArchived" then
      raise exception '% is archived and cannot be sold.', v_product.name
        using errcode = 'check_violation';
    end if;

    if v_product.inventory < v_qty then
      raise exception '% has only % in stock.', v_product.name, v_product.inventory
        using errcode = 'check_violation';
    end if;

    insert into public."OrderItem" (
      "orderId", "productSlug", "productName", quantity, "priceInCents"
    ) values (
      v_order_id, v_product.slug, v_product.name, v_qty, v_product."priceInCents"
    );

    update public."Product"
       set inventory = inventory - v_qty,
           "updatedAt" = now()
     where slug = v_product.slug;

    v_subtotal := v_subtotal + (v_qty * v_product."priceInCents");
  end loop;

  update public."Order"
     set "subtotalInCents" = v_subtotal,
         "totalInCents"    = v_subtotal + v_ship,
         "updatedAt"       = now()
   where id = v_order_id;

  return v_number;
end;
$$;

-- ── restock_order ───────────────────────────────────────────
--
-- Puts an order's units back. Idempotent by `stockReleasedAt`: the second call
-- does nothing, which is what makes CANCELLED → REFUNDED safe.

create or replace function public.restock_order(order_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_released timestamptz;
begin
  select "stockReleasedAt" into v_released
    from public."Order" where id = order_id for update;

  if not found then
    raise exception 'No order with the id %.', order_id
      using errcode = 'foreign_key_violation';
  end if;

  if v_released is not null then
    return;
  end if;

  update public."Product" p
     set inventory = p.inventory + i.quantity,
         "updatedAt" = now()
    from public."OrderItem" i
   where i."orderId" = order_id
     and p.slug = i."productSlug";

  update public."Order"
     set "stockReleasedAt" = now(),
         "updatedAt" = now()
   where id = order_id;
end;
$$;

-- ── set_order_status ────────────────────────────────────────
--
-- One entry point so "cancelled" and "the units are back on the shelf" cannot
-- come apart. The dashboard never updates `status` directly.

create or replace function public.set_order_status(
  order_id text,
  next_status public."OrderStatus"
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public."Order"
     set status = next_status,
         "updatedAt" = now()
   where id = order_id;

  if not found then
    raise exception 'No order with the id %.', order_id
      using errcode = 'foreign_key_violation';
  end if;

  if next_status in ('CANCELLED', 'REFUNDED') then
    perform public.restock_order(order_id);
  end if;
end;
$$;

-- ── Reporting ───────────────────────────────────────────────
--
-- Aggregation is Postgres's job. The alternative — pulling every order into
-- Node to sum it — gets slower with every sale and is the same arithmetic
-- performed further from the data.
--
-- Revenue here is **merchandise** revenue: the sum of the lines, excluding
-- delivery. Delivery is a cost recovered, not something sold, and mixing it in
-- would make the top-products figures and the daily total disagree.
--
-- Cancelled and refunded orders are excluded from both: they are sales that
-- un-happened, and a chart that counts them reports money the boutique does
-- not have.
--
-- `security_invoker = on` so the views cannot be used as a way around the RLS
-- on the tables beneath them.

create or replace view public."DailySales"
with (security_invoker = on) as
select
  (o."placedAt" at time zone 'UTC')::date               as day,
  o.channel                                             as channel,
  count(distinct o.id)::int                             as "orderCount",
  coalesce(sum(i.quantity), 0)::int                     as units,
  coalesce(sum(i.quantity * i."priceInCents"), 0)::bigint as "revenueInCents"
from public."Order" o
join public."OrderItem" i on i."orderId" = o.id
where o.status not in ('CANCELLED', 'REFUNDED')
group by 1, 2;

create or replace view public."ProductSales"
with (security_invoker = on) as
select
  i."productSlug"                                       as "productSlug",
  max(i."productName")                                  as "productName",
  sum(i.quantity)::int                                  as units,
  sum(i.quantity * i."priceInCents")::bigint            as "revenueInCents",
  max(o."placedAt")                                     as "lastSoldAt"
from public."OrderItem" i
join public."Order" o on o.id = i."orderId"
where o.status not in ('CANCELLED', 'REFUNDED')
group by 1;

-- Parameterised reads. A view cannot take "the last 30 days" as an argument,
-- and building that filter as a PostgREST string is the pattern
-- `src/lib/admin/filter.ts` argues against.

create or replace function public.daily_sales(days int)
returns table (
  day text,
  "orderCount" int,
  units int,
  "revenueInCents" bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    to_char(d.day, 'YYYY-MM-DD'),
    sum(d."orderCount")::int,
    sum(d.units)::int,
    sum(d."revenueInCents")::bigint
  from public."DailySales" d
  where d.day >= (current_date - greatest(days, 1) + 1)
  group by d.day
  order by d.day;
$$;

create or replace function public.product_sales(days int, row_limit int default 8)
returns table (
  "productSlug" text,
  "productName" text,
  units int,
  "revenueInCents" bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    i."productSlug",
    max(i."productName"),
    sum(i.quantity)::int,
    sum(i.quantity * i."priceInCents")::bigint
  from public."OrderItem" i
  join public."Order" o on o.id = i."orderId"
  where o.status not in ('CANCELLED', 'REFUNDED')
    and o."placedAt" >= (now() - make_interval(days => greatest(days, 1)))
  group by i."productSlug"
  order by 4 desc
  limit greatest(row_limit, 1);
$$;

create or replace function public.channel_split(days int)
returns table (
  channel text,
  "orderCount" int,
  "revenueInCents" bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    o.channel::text,
    count(distinct o.id)::int,
    coalesce(sum(i.quantity * i."priceInCents"), 0)::bigint
  from public."Order" o
  join public."OrderItem" i on i."orderId" = o.id
  where o.status not in ('CANCELLED', 'REFUNDED')
    and o."placedAt" >= (now() - make_interval(days => greatest(days, 1)))
  group by o.channel;
$$;

-- ── Row level security ──────────────────────────────────────
--
-- On, with no policy at all. Not an oversight: see the trust model above.
-- Every read and every write holds the secret key and runs on the server.

alter table public."Order"     enable row level security;
alter table public."OrderItem" enable row level security;

drop policy if exists "Orders are readable"     on public."Order";
drop policy if exists "Order items are readable" on public."OrderItem";

-- ── Privileges ──────────────────────────────────────────────
--
-- `0006_privileges.sql` runs *before* this file, so its
-- `alter default privileges … grant select on tables` applies to everything
-- created here. For the catalog that default is right; for a table of customer
-- names and phone numbers it is not. Taken back explicitly, and the sales
-- views with it — a view without `security_invoker` would otherwise be a hole
-- straight through the RLS above, and even with it there is no reason for a
-- browser key to see revenue.

revoke all on public."Order"       from anon, authenticated;
revoke all on public."OrderItem"   from anon, authenticated;
revoke all on public."DailySales"  from anon, authenticated;
revoke all on public."ProductSales" from anon, authenticated;
revoke all on sequence public.order_number_seq from anon, authenticated;

-- ⚠ `from public`, not just `from anon, authenticated`.
--
-- Postgres grants EXECUTE on every new function to the pseudo-role PUBLIC,
-- which every role inherits. Revoking from `anon` and `authenticated` by name
-- leaves that inherited grant untouched, so the browser key can still call
-- them — and `place_order()` is `security definer`, so calling it writes an
-- order and moves stock with the owner's rights. This was proved by asking the
-- publishable key to place an order: before this revoke it succeeded.
--
-- The role-specific revokes stay beside it. They are redundant today and stop
-- being redundant the moment anybody grants either role explicitly.
revoke all on function public.place_order(jsonb)                          from public, anon, authenticated;
revoke all on function public.restock_order(text)                         from public, anon, authenticated;
revoke all on function public.set_order_status(text, public."OrderStatus") from public, anon, authenticated;
revoke all on function public.daily_sales(int)                            from public, anon, authenticated;
revoke all on function public.product_sales(int, int)                     from public, anon, authenticated;
revoke all on function public.channel_split(int)                          from public, anon, authenticated;

grant all on public."Order", public."OrderItem" to service_role;
grant select on public."DailySales", public."ProductSales" to service_role;
grant usage on sequence public.order_number_seq to service_role;
grant execute on function public.place_order(jsonb)                          to service_role;
grant execute on function public.restock_order(text)                         to service_role;
grant execute on function public.set_order_status(text, public."OrderStatus") to service_role;
grant execute on function public.daily_sales(int)                            to service_role;
grant execute on function public.product_sales(int, int)                     to service_role;
grant execute on function public.channel_split(int)                          to service_role;
