-- KHEM — the Inner Circle, as a list rather than as a pile of emails.
--
-- Applied by `npm run db:migrate` after `0024_customers.sql`, whose `"User"`
-- rows this cross-references by Clerk id, and after `0006_privileges.sql` —
-- hence the explicit revoke at the bottom, same as 0015 and 0024.
--
-- `src/services/admin/newsletter.ts` reads these; `src/actions/newsletter.ts`
-- and `src/app/api/webhooks/clerk/route.ts` write them.
--
-- ── What this replaces ──────────────────────────────────────
--
-- `src/actions/newsletter.ts` used to email the house inbox and store nothing:
-- a subscription was a message somebody had to act on by hand. That was honest
-- while there was no list, and it is the thing this file ends. Three
-- consequences follow, and all three are the point:
--
--  1. **Consent becomes provable.** `consentAt` records when the address was
--     given. A bare "they're on the list" cannot answer "since when, and on
--     what basis", which is the only question that matters if it is challenged.
--  2. **Unsubscribing becomes real.** The old welcome letter asked people to
--     *reply* and be removed by hand. `unsubscribe_newsletter()` and the token
--     below make the link in that letter do what it says.
--  3. **A withdrawal is never a deletion.** Unsubscribing flips the status and
--     stamps `unsubscribedAt`; the row stays. A deleted row cannot prove that
--     consent was withdrawn, and cannot stop the address being re-added by a
--     later import.
--
-- ── The token, and why it is not the id ─────────────────────
--
-- The unsubscribe link travels in an email, which means it travels in plain
-- text through servers nobody here controls, and it must work for somebody who
-- is not signed in and may not even have an account. Addressing it by row id
-- would let anyone who can count unsubscribe anyone.
--
-- So each row carries its own random `unsubscribeToken` — 64 hex characters
-- from two v4 UUIDs, ~244 bits, generated by the database and never derived
-- from anything about the subscriber. Guessing one is not a thing that happens.
--
-- Chosen over an HMAC of the id, which was the other candidate: an HMAC needs a
-- signing secret in the environment, and a deployment that has not got one
-- either cannot honour unsubscribes at all or has to fall back to something
-- weaker. A per-row random value needs no key management and cannot be
-- invalidated by a rotation nobody remembered was load-bearing.
--
-- ── Trust model ─────────────────────────────────────────────
--
-- Same as `"User"`: these rows are email addresses belonging to real people.
-- RLS on, **no policy of any kind**, no grant to the public roles. Everything
-- reaches them through the secret key — the dashboard behind `requireAdmin()`,
-- the signup action, the Clerk webhook, and the unsubscribe route, which
-- authorises by token rather than by session.

-- ── Enums ───────────────────────────────────────────────────

do $$ begin
  create type public."NewsletterStatus" as enum ('SUBSCRIBED', 'UNSUBSCRIBED');
exception when duplicate_object then null; end $$;

-- Where the address came from. Worth recording because the three carry
-- different evidence of consent: a form the person filled in, a box they ticked
-- while making an account, and somebody at the desk typing it in.
do $$ begin
  create type public."NewsletterSource" as enum ('HOME_FORM', 'SIGN_UP', 'ADMIN');
exception when duplicate_object then null; end $$;

-- ── NewsletterSubscriber ────────────────────────────────────

create table if not exists public."NewsletterSubscriber" (
  id                 text primary key default gen_random_uuid()::text,

  email              text not null check (char_length(email) <= 254),

  status             public."NewsletterStatus" not null default 'SUBSCRIBED',
  source             public."NewsletterSource" not null default 'HOME_FORM',

  -- Which language the house writes to them in. Same two-value rule as
  -- `"Order".locale`, and the same reason: a letter in the wrong language is a
  -- letter nobody reads.
  locale             text not null default 'en' check (locale in ('en', 'ar')),

  -- Soft link to the account, when there is one. No foreign key, for the same
  -- reason `"Order"."clerkUserId"` has none: a subscriber need not have an
  -- account, and a webhook that is late must not fail a signup.
  "clerkUserId"      text,

  -- See the header. Random per row, never derived, never reused.
  "unsubscribeToken" text not null
    default replace(gen_random_uuid()::text, '-', '')
         || replace(gen_random_uuid()::text, '-', ''),

  -- When consent was last *given*. Moved by a re-subscription, because that is
  -- a fresh act of consent; untouched by an ordinary profile edit.
  "consentAt"        timestamptz not null default now(),

  -- When it was withdrawn. Null while subscribed, and cleared again on a
  -- genuine re-subscription so the pair never describes two states at once.
  "unsubscribedAt"   timestamptz,

  "createdAt"        timestamptz not null default now(),
  "updatedAt"        timestamptz not null default now()
);

-- One row per address, whatever its case. Not partial like `"User"`'s: an
-- unsubscribed row must still block a second row for the same address, or a
-- re-signup would silently resurrect somebody who asked to be left alone.
create unique index if not exists newsletter_email_idx
  on public."NewsletterSubscriber" (lower(email));

create unique index if not exists newsletter_token_idx
  on public."NewsletterSubscriber" ("unsubscribeToken");

create index if not exists newsletter_status_idx
  on public."NewsletterSubscriber" (status, "createdAt" desc);

-- ── subscribe_newsletter ────────────────────────────────────
--
-- Idempotent by construction. Returns what the caller needs to decide whether a
-- welcome letter is owed:
--
--   { id, token, isNew, reactivated }
--
-- `isNew` — the address had never been seen.
-- `reactivated` — it was on the list, had unsubscribed, and has now come back.
--
-- Either warrants the welcome. Neither being true means the address was already
-- subscribed, and sending again would be the house mailing somebody for filling
-- in a form twice.

create or replace function public.subscribe_newsletter(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email  text := lower(btrim(nullif(payload->>'email', '')));
  v_locale text := coalesce(nullif(payload->>'locale', ''), 'en');
  v_source public."NewsletterSource" :=
             coalesce((payload->>'source')::public."NewsletterSource", 'HOME_FORM');
  v_clerk  text := nullif(payload->>'clerkUserId', '');
  v_row    record;
  v_id     text;
  v_token  text;
begin
  if v_email is null then
    raise exception 'A subscription needs an email address.'
      using errcode = 'check_violation';
  end if;

  if v_locale not in ('en', 'ar') then
    v_locale := 'en';
  end if;

  select s.id, s.status, s."unsubscribeToken"
    into v_row
    from public."NewsletterSubscriber" s
   where lower(s.email) = v_email;

  if not found then
    insert into public."NewsletterSubscriber" (email, locale, source, "clerkUserId")
    values (v_email, v_locale, v_source, v_clerk)
    returning id, "unsubscribeToken" into v_id, v_token;

    return jsonb_build_object(
      'id', v_id, 'token', v_token, 'isNew', true, 'reactivated', false
    );
  end if;

  update public."NewsletterSubscriber"
     set status           = 'SUBSCRIBED',
         locale           = v_locale,
         -- The account link is filled in, never cleared: an address that
         -- subscribed anonymously and later signed in keeps the connection.
         "clerkUserId"    = coalesce(v_clerk, "clerkUserId"),
         -- A fresh act of consent, whether or not they had lapsed.
         "consentAt"      = now(),
         "unsubscribedAt" = null,
         "updatedAt"      = now()
   where id = v_row.id;

  return jsonb_build_object(
    'id', v_row.id,
    'token', v_row."unsubscribeToken",
    'isNew', false,
    'reactivated', v_row.status = 'UNSUBSCRIBED'
  );
end;
$$;

-- ── unsubscribe_newsletter ──────────────────────────────────
--
-- By token, never by id — see the header.
--
-- Idempotent on purpose: somebody who clicks the link twice, or whose mail
-- client fetches it twice, must see "you are unsubscribed" both times rather
-- than an error suggesting it did not work. `alreadyOff` distinguishes the two
-- for the page's wording without changing the outcome.
--
-- Returns `{ found: false }` for a token that matches nothing, which the route
-- renders as a plain "that link is not valid" — never as a hint about whether
-- some other address is on the list.

create or replace function public.unsubscribe_newsletter(token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row record;
begin
  select s.id, s.email, s.status
    into v_row
    from public."NewsletterSubscriber" s
   where s."unsubscribeToken" = token;

  if not found then
    return jsonb_build_object('found', false);
  end if;

  if v_row.status = 'UNSUBSCRIBED' then
    return jsonb_build_object('found', true, 'alreadyOff', true, 'email', v_row.email);
  end if;

  update public."NewsletterSubscriber"
     set status           = 'UNSUBSCRIBED',
         "unsubscribedAt" = now(),
         "updatedAt"      = now()
   where id = v_row.id;

  return jsonb_build_object('found', true, 'alreadyOff', false, 'email', v_row.email);
end;
$$;

-- ── newsletter_list ─────────────────────────────────────────
--
-- The dashboard's page of subscribers: searched, filtered, paginated, and
-- carrying its own total so the pager needs no second round trip. Same shape
-- and the same `position()` matching as `customer_summary()` in 0024 — a `%`
-- somebody types is a percent sign, not a wildcard.
--
-- The token is **not** in the projection. Nothing on a dashboard screen needs
-- it, and a value that unsubscribes somebody has no business in a page payload.

create or replace function public.newsletter_list(
  search_term   text default '',
  status_filter text default '',
  limit_count   int  default 50,
  offset_count  int  default 0
)
returns table (
  id               text,
  email            text,
  status           public."NewsletterStatus",
  source           public."NewsletterSource",
  locale           text,
  "clerkUserId"    text,
  "consentAt"      timestamptz,
  "unsubscribedAt" timestamptz,
  "createdAt"      timestamptz,
  "totalCount"     bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with needle as (
    select
      lower(btrim(coalesce(search_term, '')))   as q,
      nullif(btrim(coalesce(status_filter, '')), '') as st
  ),
  matched as (
    select s.*
      from public."NewsletterSubscriber" s, needle n
     where (n.q  = '' or position(n.q in lower(s.email)) > 0)
       and (n.st is null or s.status = n.st::public."NewsletterStatus")
  )
  select
    m.id, m.email, m.status, m.source, m.locale, m."clerkUserId",
    m."consentAt", m."unsubscribedAt", m."createdAt",
    count(*) over () as "totalCount"
  from matched m
  order by m."createdAt" desc
  limit greatest(1, least(coalesce(limit_count, 50), 200))
  offset greatest(0, coalesce(offset_count, 0));
$$;

-- ── newsletter_counts ───────────────────────────────────────
--
-- The three figures above the list. One query rather than three round trips,
-- and computed over the whole table rather than the page — a count that changed
-- when you turned the page would be describing the page, not the list.

create or replace function public.newsletter_counts()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'total',        count(*),
    'subscribed',   count(*) filter (where s.status = 'SUBSCRIBED'),
    'unsubscribed', count(*) filter (where s.status = 'UNSUBSCRIBED')
  )
  from public."NewsletterSubscriber" s;
$$;

-- ── Privileges ──────────────────────────────────────────────

alter table public."NewsletterSubscriber" enable row level security;

revoke all on public."NewsletterSubscriber" from public, anon, authenticated;

revoke all on function public.subscribe_newsletter(jsonb)   from public, anon, authenticated;
revoke all on function public.unsubscribe_newsletter(text)  from public, anon, authenticated;
revoke all on function public.newsletter_list(text, text, int, int)
  from public, anon, authenticated;
revoke all on function public.newsletter_counts()           from public, anon, authenticated;
