"use server";

/**
 * Journal writes.
 *
 * Same trust model as `actions/admin/catalog.ts`: `requireAdmin()` first,
 * Zod second, service key third, and no RLS policy added anywhere to make it
 * work. See that file's header for the reasoning in full.
 *
 * The one thing peculiar to articles: `isPublished` is the visibility switch
 * the public policy on `"Article"` reads, so an unpublished row is invisible to
 * the storefront without being deleted. That is what makes drafting possible
 * here at all, and it is why there is no delete action — a retired article
 * becomes a draft rather than a hole in the archive.
 */

import { requireAdmin } from "@/src/lib/admin/auth";
import { revalidateArticle } from "@/src/lib/admin/revalidate";
import { embedDocument, toVectorLiteral } from "@/src/lib/search/embed";
import { getSupabaseAdmin } from "@/src/lib/supabase";
import {
  createArticleSchema,
  setArticlePublishedSchema,
  updateArticleSchema,
  type AdminActionResult,
} from "@/src/schemas/admin";

import {
  UNCONFIGURED,
  fieldErrorsFrom,
  postgresFailure,
  type PostgresErrorLike,
} from "./shared";

/**
 * Give a saved article a vector, best effort.
 *
 * The twin of `refreshProductEmbedding()` in `actions/admin/catalog.ts`, and it
 * reads `search_document` back from the database for the same reason: that
 * column is generated by Postgres, and rebuilding the string here would put the
 * embedding in a different space from every article `npm run embed` has
 * processed.
 *
 * Unlike the product path, this write actually persists.
 * `article_embedding_invalidation` (supabase/sql/0009_journal.sql) also
 * compares the embeddings, so the statement that stores a fresh vector is not
 * mistaken for an edit to the text and nulled out again — see the note in that
 * file, and the standing bug it describes on the product trigger.
 *
 * Every failure path is a warning and a return, never a throw: the article is
 * already saved. An article with no vector still appears in the related rail,
 * ranked by category and recency, which is what the fallback ordering is for.
 */
async function refreshArticleEmbedding(slug: string): Promise<void> {
  const supabase = getSupabaseAdmin();
  if (!supabase) return;

  const { data, error } = await supabase
    .from("Article")
    .select("search_document")
    .eq("slug", slug)
    .maybeSingle();

  if (error || !data) {
    console.warn(
      `[admin] Could not read search_document for article ${slug}: ${error?.message ?? "no row"}`,
    );
    return;
  }

  const document = (data as { search_document: string | null }).search_document;
  if (typeof document !== "string") return;

  const vector = await embedDocument(document);
  if (vector === null) return;

  const { error: writeError } = await supabase
    .from("Article")
    .update({ embedding: toVectorLiteral(vector) })
    .eq("slug", slug);

  if (writeError) {
    console.warn(
      `[admin] Embedding not stored for article ${slug}: ${writeError.message}. ` +
        "Run `npm run embed` to fill it in.",
    );
  }
}

export async function createArticle(input: unknown): Promise<AdminActionResult> {
  const actor = await requireAdmin();

  const parsed = createArticleSchema.safeParse(input);
  if (!parsed.success) {
    return {
      ok: false,
      message: "Some fields need attention.",
      fieldErrors: fieldErrorsFrom(parsed.error),
    };
  }

  const supabase = getSupabaseAdmin();
  if (!supabase) return UNCONFIGURED;

  const { slug, ...rest } = parsed.data;

  const { error } = await supabase.from("Article").insert({
    id: slug,
    slug,
    ...rest,
  });

  if (error) {
    console.error(`[admin] createArticle rejected (${actor.email}): ${error.message}`);
    return postgresFailure(error as PostgresErrorLike, "article");
  }

  await refreshArticleEmbedding(slug);

  revalidateArticle(slug);
  console.log(`[admin] article created by ${actor.email} → ${slug}`);

  return {
    ok: true,
    slug,
    message: parsed.data.isPublished
      ? `"${parsed.data.title}" published.`
      : `"${parsed.data.title}" saved as a draft.`,
  };
}

export async function updateArticle(input: unknown): Promise<AdminActionResult> {
  const actor = await requireAdmin();

  const parsed = updateArticleSchema.safeParse(input);
  if (!parsed.success) {
    return {
      ok: false,
      message: "Some fields need attention.",
      fieldErrors: fieldErrorsFrom(parsed.error),
    };
  }

  const supabase = getSupabaseAdmin();
  if (!supabase) return UNCONFIGURED;

  // The slug identifies the row and is never part of the payload — an article
  // URL that has been shared or indexed must keep working.
  const { slug, ...rest } = parsed.data;

  const { data, error } = await supabase
    .from("Article")
    .update(rest)
    .eq("slug", slug)
    .select("slug")
    .maybeSingle();

  if (error) {
    console.error(`[admin] updateArticle rejected (${actor.email}): ${error.message}`);
    return postgresFailure(error as PostgresErrorLike, "article");
  }

  if (!data) {
    return { ok: false, message: "That article no longer exists." };
  }

  await refreshArticleEmbedding(slug);

  revalidateArticle(slug);
  console.log(`[admin] article updated by ${actor.email} → ${slug}`);

  return { ok: true, slug, message: `"${parsed.data.title}" saved.` };
}

/** Publish or retire an article without opening the editor. */
export async function setArticlePublished(
  input: unknown,
): Promise<AdminActionResult> {
  const actor = await requireAdmin();

  const parsed = setArticlePublishedSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, message: "That request was not understood." };
  }

  const supabase = getSupabaseAdmin();
  if (!supabase) return UNCONFIGURED;

  const { slug, isPublished } = parsed.data;

  const { data, error } = await supabase
    .from("Article")
    .update({ isPublished })
    .eq("slug", slug)
    .select("slug")
    .maybeSingle();

  if (error) {
    console.error(`[admin] setArticlePublished rejected (${actor.email}): ${error.message}`);
    return postgresFailure(error as PostgresErrorLike, "article");
  }

  if (!data) {
    return { ok: false, message: "That article no longer exists." };
  }

  revalidateArticle(slug);
  console.log(
    `[admin] article ${isPublished ? "published" : "unpublished"} by ${actor.email} → ${slug}`,
  );

  return {
    ok: true,
    slug,
    message: isPublished
      ? "Published — it is live on the journal."
      : "Returned to draft. It is no longer on the journal.",
  };
}
